### ISSUE TITLE
Hardware and time used for training?

### ISSUE THREAD

**Issue by BrightMoonStar** [mihdalal/raps#12]
Hi~
Could you share which hardware setup you used for training and roughly how long one training run took on that setup?
Thanks a lot !

**Comment by mihdalal** [comment]
Hi, 
Thank you for your interest in our paper! 
From Section 4 of the paper: "To ensure consistency, we evaluate all methods on a single RTX 2080 GPU with 10 CPUs and
50GB of memory." For the length of training runs - it depends on the environment (see the plots wrt to wall clock time) but the max we ran any experiment for was 3 days.

**Comment by BrightMoonStar** [comment]
Oh, sorry, I miss it.
Thank you !
